### ISSUE TITLE
broken link in "EarthCube Resource Registry" to ngds.org

### ISSUE THREAD

**Issue by 7yl4r** [earthcubearchitecture-ecresourcereg/DataEntry#2]
Looking at the [EarthCube Resource Registry Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfqyga5GGjKNB9CeQjO0kdIDaQ38A5nINXwBc-lmTTozMmP3w/viewform) there is a broken link to ngds.org:

"-- browse catalog, http://ngds.org/487557o  --"

It looks like the registry for ngds.org expired and the domain is now for sale. 
The link needs to be fixed or removed.

Also: where can I browse the catalog now?

**Comment by smrgeoinfo** [comment]
Tyler, thanks for the heads up.  That is actually just an example labeled link, not an actual link to the ECRR catalog. Its fixed now to a live link.  The link in the list below that example:
"Browse and search EC resources with SuAVE: **https://tinyurl.com/2view-ecrr** "
is the best current UI we have for browsing the catalog
If you're interested in geothermal data, https://data.geothermaldata.org/ is a good place to go.

at https://beta.geocodes.earthcube.org/landing.html if you click the 'Tool' radio button, you'll also get a list of whatis in teh resource registry, along with some random stuff that p418 collected in the dataset harvesting.

**Comment by 7yl4r** [comment]
Thanks! One more unrelated question if you don't mind: I might like to build a tool browsing frontend like SuAVE. I have a different appearance in mind and would love for it to be RESTful. Is there an API for interacting with the catalog? Should I just pull the spreadsheet from Gdrive and go from there?

**Comment by smrgeoinfo** [comment]
At this point the only API is the SPARQL endpoint.  I can give you the info via e-mail. We have been discussing what kind of UI would be more useful, and perhaps we could collaborate on developing a new one.  Let's talk!
